// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu-container': string;
  'menu-container__menu-fn': string;
  'menu-container__menu-fn-block': string;
}
export const cssExports: CssExports;
export default cssExports;
