// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'display-img': string;
  'display-img__next': string;
  'display-img__photo': string;
  'display-img__prev': string;
}
export const cssExports: CssExports;
export default cssExports;
