// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header__btn-container': string;
  'header__btn-container__bulk-edit-btn-container': string;
  'header__title': string;
}
export const cssExports: CssExports;
export default cssExports;
