// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'login-form': string;
  'login-form__login-input': string;
  'login-form__validation': string;
}
export const cssExports: CssExports;
export default cssExports;
