// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'photo-card': string;
  'photo-card__bulk-checkbox': string;
  'photo-card__image': string;
  'photo-card__info': string;
  'photo-card__info-title': string;
  'photo-card__meatballs-menu': string;
  'photo-card__photo-card-content': string;
}
export const cssExports: CssExports;
export default cssExports;
